### ISSUE TITLE
如何更改组件内部的全局样式

### ISSUE THREAD

**Issue by boomsi** [umijs/dumi#1060]
### Question

比如我在组件内添加一个 `init.less`，希望在每个组件都应用此样式文件，并且不影响使用该组件的项目

### Sample Code

目前是这样实现，但是发现会影响应用此组件的项目本身，污染全局样式

init.less 文件
```less
a {
  color: inherit;
  text-decoration: none;
}
```

global.less 文件
```less
@import './init.less';

// others...
```

组件样式代码文件(ex: Button.less)
```less
@import 'global.less';

// others...
```
