### ISSUE TITLE
bug: Navs下划线指示器同时选中

### ISSUE THREAD

**Issue by ldwonday** [umijs/dumi#1150]
index.md配置：

```
---
title: 简介
order: 10
toc: menu
group:
  path: /
nav:
  title: 文档
  order: 1
  path: /
---
```

快速开始.md配置如下：
```
---
title: 快速开始
toc: menu
group:
  path: /
nav:
  title: 文档
  path: /
---
```

组件.md配置如下

```
---
title: ThorTable - 表格
order: 1
group:
  path: /
nav:
  order: 1
  title: 组件
  path: /components
---
```

结果现在是首页渲染正常：
![image](https://user-images.githubusercontent.com/4630157/180740153-482185ea-46b4-42e5-95fe-6404a36bd2fc.png)

选中组件nav后会出现下划线指示器同时选中的bug
![image](https://user-images.githubusercontent.com/4630157/180739114-8983a0e5-8a5f-4506-90e3-132cebf6e121.png)
