### ISSUE TITLE
bug: features link 好像没生效？

### ISSUE THREAD

**Issue by Go7hic** [umijs/dumi#1344]
### Versions

- dumi: 2.0.7
- node: v16.10.0
- npm:  7.24.0
- OS: Mac
- Browser: chrome

### Steps to reproduce
按照文档 https://d.umijs.org/config/markdown#features 在首页md文件设置 features 添加 link
```
features:
  - emoji: 💻
    title: baidu
    link: http://baidu.com
    description: baidu
  - emoji: 📈 
    title: dumi
    link: http://dumi.com 
    description: dumi2
```
页面没有超链接效果
<img width="971" alt="image" src="https://user-images.githubusercontent.com/3821390/205060615-20345f2c-024b-40ba-a557-eeb8f1c81e17.png">

### What is Expected?

应该有超链接效果
