### ISSUE TITLE
bug: dumi-theme-mobile 主题包 dumi-mobile-demo-layout 应该删除 padding

### ISSUE THREAD

**Issue by zix2002** [umijs/dumi#1423]
DemoLayout.less 文件

```less
@import (reference) '../styles/variables.less';

.@{prefix}-demo-layout {
  padding: 16px 12px; // 应该删除此行
  min-height: 100vh;
  box-sizing: border-box;
}
```
