### ISSUE TITLE
取消Footer的时候，下方padding为0，看着很难受

### ISSUE THREAD

**Issue by wizcheu** [umijs/dumi#1510]
https://github.com/umijs/dumi/blame/8e94e51886f025ef5c13412a91a4a35bcf7f6a00/src/client/theme-default/slots/Content/index.less#L150

**Comment by Wxh16144** [comment]
我来尝试解决一下～

**Comment by Wxh16144** [comment]
方案一：

在 layout 中添加一个css选择器判断有没有 footer ， has 有兼容性问题 [can i use](https://caniuse.com/?search=%3Ahas)
```less
  &:not(&:has(> .@{prefix}-footer)) {
    margin-bottom: @s-content-padding;
  }

```

方案二：

同 sidebar 逻辑一个加一个自定义属性
