### ISSUE TITLE
首页按钮怎么使用外链？

### ISSUE THREAD

**Issue by Lands-1203** [umijs/dumi#1685]
### Question
![image](https://github.com/umijs/dumi/assets/61341868/f2765818-f317-4e79-8064-72bc0495b2ea)
![image](https://github.com/umijs/dumi/assets/61341868/a8639cdb-6ed9-4385-9bc1-e3cced9e8319)
![image](https://github.com/umijs/dumi/assets/61341868/63e651d9-4352-4d30-be0e-fd52609c2f00)

### Sample Code

```
---
hero:
  title: 前端React组件库
  description: 'xxxx'
  actions:
    - text: 开始使用
      link: /guide/development-description
    - text: Code
      link: https://baidu.com/
---
```
