### ISSUE TITLE
bug: 顶部二级菜单文字换行问题

### ISSUE THREAD

**Issue by whinc** [umijs/dumi#1865]
### Versions

- dumi: 2.2.7
- node: 16
- npm:
- OS: centos 7
- Browser: chrome

### Steps to reproduce

二级菜单项的文字比一级菜单的文字多时，会出现换行，例如下面两个二级菜单项【提 Issue】和【XXX 平台】
![image](https://github.com/umijs/dumi/assets/5096493/8a4769cc-97f1-4426-b725-e95a70977691)

### What is Expected?

二级菜单项默认展示完整内容不换行，类似 antd Select 组件的 dropdownMatchSelectWidth 为  false 的行为

![image](https://github.com/umijs/dumi/assets/5096493/1f0f81ac-9670-4a54-8e5c-2377943e15ff)

目前暂时通过覆盖样式解决
```css
.dumi-default-navbar > li > .dumi-default-navbar-dropdown {
  white-space: nowrap;
}
```
