### ISSUE TITLE
dumi升级到2.0后,src中的import less报错了，应该如何修改呢？

### ISSUE THREAD

**Issue by fanhualei** [umijs/dumi#1897]
### Question
dumi升级到2.0后,src中的import less报错了，应该如何修改呢？

### Sample Code
index.css

```css
.title{
    font-size: 15px;
    color: red;
  }
```

index.tsx

```js
import React from 'react'

import Styles from './index.less';

const Test: React.FC = () => {
    return (
      <div className='Styles.title' >
           ddddd bbbbbbbbbbb
      </div>
    );
  };
  
  export default Test;
```
