### ISSUE TITLE
feat: meta link 支持外链，且支持开一个新tab弹出

### ISSUE THREAD

**Issue by FateRiddle** [umijs/dumi#269]
```
---
title: Form Render
hero:
  title: FormRender
  desc: 通过 JSON Schema 生成标准 Form，常用于自定义搭建配置界面生成
  actions:
    - text: 开始使用
      link: /guide/getting-started
    - text: playground
      link: https://www.taobao.com
      target: _blank
---
```

真实场景里需要link能跳外链。且跳外链的情况一般希望能开一个新tab，所以希望支持如上的配置
```
    - text: playground
      link: https://www.taobao.com
      target: _blank
```
