### ISSUE TITLE
是否可以支持通过配置routes或者includes的方式引入其他项目内的md文件

### ISSUE THREAD

**Issue by xjl271314** [umijs/dumi#314]
### Question

需求描述:

为了单独将文档抽离出来,不放在主项目的包中,希望可以在主项目中指定目录下编写符合dumi语法格式的md文件,对于dumi生成的文档新建一个单独的项目,在dumi中配置加载主项目的md文件 或者进行配置嗅探指定目录下的md文件。

例如在config下进行如下这种配置

```
routes: [
      { path: '/aa', component: 'https://gitlab.com/yourProject/README.md' },
],
```
或者是
```
resolve: {
     includes: ['https://gitlab.com/yourProject/category'],
}
```
主要是为了防止文档对线上主项目产生了影响,不知道是否可以支持读取外部的md文件??

**Comment by PeachScript** [comment]
访问远程仓库的权限取决于宿主环境，会影响 CI、CD，dumi 目前不会考虑做这个功能；另外没理解『防止文档对线上主项目产生了影响』具体是指什么。

如果很 care 这个场景，有两个建议的解法手动实现：
1. 写 sync 脚本从主仓库同步 md 到文档仓库
2. 利用 git submodules 来管理文档与 dumi 站点仓库及主仓库之前的关系，比如：
```yaml
Repo 1: 文档 md
Repo 2: dumi 站点
  - Sub Module: Repo 1
Repo 3: 组件库
  - Sub Module: Repo 1
```
