### ISSUE TITLE
feat: 给 layout 添加当前路由属性以便复写样式

### ISSUE THREAD

**Issue by mizi-lin** [umijs/dumi#346]
当前 一个一级目录下 拥有多个group 
sidemenu 会将 所有的group以及该group下的子文件显示

建议：可以设置 只显示 pathname 所在的group 的相关信息，不需要显示其他 group 信息

**Comment by PeachScript** [comment]
是指 site 模式吗？

**Comment by mizi-lin** [comment]
@PeachScript  是的

比如两个 group A 和 B  同属于 document, 但A和B 其实没有任何关系，
所以在查看A的子级的时候，不想看到B的内容，而且还有C,D,E,F,G,H等，就会造成 sidemenu 过长
虽然直接将 group A 和 B 升级成 nav(一级目录) 也可以达到需求
但还是更想用  /document/A/xxx,  /document/B/xxx 访问, 更据语义化
强迫症所在~

**Comment by PeachScript** [comment]
这个点比较细，dumi 层面是没法开配置项来做了，否则配置会泛滥；但听下来应该可以通过类似的 CSS 实现：

```css
.__dumi-default-menu-list > li > a:not(.active) + ul {
  display: none;
}
```
