### ISSUE TITLE
does not support import remote css as less in less files

### ISSUE THREAD

**Issue by RunningCoderLee** [umijs/dumi#775]
### Versions

- dumi: 1.1.23
- node: v14.15.4
- npm: 6.14.11
- OS: macOS Big Sur 11.2.3
- Browser: Edge 91.0.864.67

### Steps to reproduce

在组件的 `less` 样式文件里通过 `@import` 语法引入 web url 地址

```less
@import (less) url('https://at.alicdn.com/t/font_2673961_hg2vb7cj7i.css');

.a {
  color: red;
}

```

### What is Expected?

正确加载

### What is actually happening?

启动时报错

![image](https://user-images.githubusercontent.com/13218863/125836666-e512f655-eb65-497b-bfb9-c706bcd49296.png)
