### ISSUE TITLE
bug: md配置hero不起作用

### ISSUE THREAD

**Issue by 799953468** [umijs/dumi#784]
### Versions

- dumi: 1.1.23
- node: 14.17.3
- npm: 6.14.13
- OS: mac
- Browser: edge
 
### Steps to reproduce
```
---
hero:
    title: dianze-ui
    actions:
        - text: Getting Started
        link: /guide
---
```
### What is actually happening?
![企业微信20210720-161749](https://user-images.githubusercontent.com/30137019/126286469-7db113f4-0db1-40c9-a6e8-c8679cae7e15.png)
