### ISSUE TITLE
FrontMatter不生效

### ISSUE THREAD

**Issue by RuiCaiSmile** [umijs/dumi#822]
### Question
用`yarn create @umijs/dumi-lib`创建的项目，md文档中的FrontMatter只有 title等少数属性生效，同样的配置在站点模式的项目是神效的
### Sample Code
```
---
hero:
  title: 测试title
  actions:
    - text: Getting Started
      link: /Start
footer: Powered by [dumi](https://d.umijs.org)
---
```
