### ISSUE TITLE
如何在demo示例中添加自定义样式

### ISSUE THREAD

**Issue by liutaochange** [umijs/dumi#951]
### 以 antd 的demo为例

![image](https://user-images.githubusercontent.com/21559008/142712177-b399c4e5-ff76-4e81-98b1-a60e8c6ee4b7.png)

希望这里的 site-custom-tab-bar css 类名，可以生效 

我目前的做法是在md文档里通过  ```css  代码块来写样式，如下：

```css
.site-custom-tab-bar {
  z-index: 1;
  background: #fff;
}
```
但是不生效，dumi 版本是 1.0.14
